# Generated by Django 3.0.5 on 2020-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Patient Name', max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(default='Male', max_length=100)),
            ],
        ),
    ]
